
# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build-python3.8:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "test-requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            sudo python -m pip install --upgrade pip
            sudo python -m pip install --upgrade -r test-requirements.txt

      - run:
          name: run tests
          command: |
            tox

  build-python3.9:
    docker:
      - image: circleci/python:3.9
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "test-requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            sudo python -m pip install --upgrade pip
            sudo python -m pip install --upgrade -r test-requirements.txt

      - run:
          name: run tests
          command: |
            tox

  build-python3.10:
    docker:
      - image: circleci/python:3.10
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "test-requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            sudo python -m pip install --upgrade pip
            sudo python -m pip install --upgrade -r test-requirements.txt
      - run:
          name: run tests
          command: |
            tox

  build-python3.11:
    docker:
      - image: circleci/python:3.11
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "test-requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            sudo python -m pip install --upgrade pip
            sudo python -m pip install --upgrade -r test-requirements.txt
      - run:
          name: run tests
          command: |
            tox

workflows:
  version: 2
  build:
    jobs:
      - build-python3.8
      - build-python3.9:
          requires:
            - build-python3.8
      - build-python3.10:
          requires:
            - build-python3.8
      - build-python3.11:
          requires:
            - build-python3.8
